name: "Deploy to GitHub Pages"

# Most of the following configuration came from "Simple workflow for deploying static content to GitHub Pages".

on:
  push:
    branches:
      - master
      - main
  # Allow for an on-demand (manually) deployment.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - mideal-embedding-angular
          - mideal-embedding-on-html

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Node.js
        if: matrix.project == 'mideal-embedding-angular'
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'

      - name: Install dependencies
        if: matrix.project == 'mideal-embedding-angular'
        run: npm ci
        working-directory: ${{ matrix.project }}

      - name: Build Angular to static assets
        if: matrix.project == 'mideal-embedding-angular'
        run: npm run build
        working-directory: ${{ matrix.project }}

      - name: Copy static HTML project
        if: matrix.project == 'mideal-embedding-on-html'
        run: cp -R ./mideal-embedding-on-html ./dist/mideal-embedding-on-html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ matrix.project == 'mideal-embedding-angular' && 'dist/mideal-embedding-angular' || 'dist/mideal-embedding-on-html' }}
          publish_branch: gh-pages
          destination_dir: ${{ matrix.project }}
